ld-neonscience:
    container_name: ld-neonscience
    build: ./trifid-neon
    ports: 
      - 80:8080
    links:
      - fuseki-neonscience
    volumes:
      - ./data/config-custom.json:/app/config.json
    environment:
      - TRIFID_CONFIG=/app/config-custom.json

fuseki-neonscience:
    container_name: fuseki-neonscience
    build: ./fuseki-geosparql-docker
    volumes:
      - ./data/abby_road.rdf:/jena-fuseki/geosparql_test.rdf
#    ports:
#      - 3030:3030
    expose:
      - "3030"
